# Multi-stage Dockerfile to build and serve the React application
# Stage 1: Build the React application
FROM node:20 AS build

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "dev"]
